datos = open('datos.txt')
linea1 = datos.readline()
linea2 = datos.readline()
datos.close()
print(linea1)
print('Largo de la linea: ', len(linea1))
lista = linea1.split(',')
print(lista)
print(len(lista))
